on: [push]

name: ci

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
            components: rustfmt, clippy
      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
            components: rustfmt, clippy
      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
            components: rustfmt, clippy
      - name: Run cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
  docker:
    name: Build docker container
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Login
      run: docker login docker.pkg.github.com -u bahlo -p "${{ secrets.GITHUB_TOKEN }}"
    - name: Build
      run: docker build -t docker.pkg.github.com/bahlo/discord-retention-bot/discord-retention-bot:latest .
    - name: Publish
      run: docker push docker.pkg.github.com/bahlo/discord-retention-bot/discord-retention-bot:latest
